### ISSUE TITLE
'HitsTableController' is unavailable: Use your own UITableViewController conforming to HitsController protocol

### ISSUE THREAD

**Issue by rayfarer** [algolia/instantsearch-ios#114]
**Describe the bug 🐛**
Followed the getting started guide and have been using the library for my project for a while now without problems. But recently, after updating my podfile to remove InstantSearchClient and just use InstantSearch, I'm getting an error when trying to build and run my app:

'HitsTableController' is unavailable: Use your own UITableViewController conforming to HitsController protocol 

Am I doing something wrong? I'm using InstantSearch 7.0. Is it not playing nice with the new Algolia Swift v8? I got hit with a double whammy by updating to 7, because all kinds of breaking changes to Algolia client were made recently.

**Environment:**
iOS

**Comment by rayfarer** [comment]
I see that these were marked as "Obsolete old table/collection view helpers." I guess it would just be helpful if the Getting Start guide was updated, because it still uses these obsolete components.

**Comment by VladislavFitz** [comment]
Hello @rayfarer ,

Thank you for your feedback. You are right, the Getting Started guide is not up-to-date at the moment. 
We are about to release a significant update for `InstantSearch` with lots of new helpers and the Guide will be updated accordingly. 

Stay tuned!

**Comment by rayfarer** [comment]
I'm happy to hear the guide will be updated soon. I guess I'm just a little discouraged because the obsolete HitsTableController is now preventing my app from building. Do you have any suggestions to work around this?

**Comment by rayfarer** [comment]
HOWVER, one problem I am finding is there are no clear examples of how to select an item and navigate to a details VC. See [this](https://stackoverflow.com/questions/63180618/push-new-vc-from-subview-table-view-controller/63180765?noredirect=1#comment111724583_63180765) for more details.

**Comment by VladislavFitz** [comment]
Hi @rayfarer,
Well done, this is exactly what we expect from developers as `HitsController` protocol implementation 🙂
We sunset `HitsTableController` implementation because it required the inheritance for customization. The protocol-based approach is just a bit more complicated, but is way more flexible. That's why we encourage developers to use it within long-term projects. But we might provide more implementation guides for sure. 
By the way, we have a [repository](https://github.com/algolia/instantsearch-ios-examples) containing the examples of search features implementations using InstantSearch. You can take a look at it to get inspiration for your own projects.
