### ISSUE TITLE
Sorting by field

### ISSUE THREAD

**Issue by cerupcat** [algolia/instantsearch-ios#34]
Is there an example of how to sort by a field? For example, sort by rating or sort by distance, etc. I can't seem to find an example.

**Comment by spinach** [comment]
Hey @cerupcat,

Indeed we don't have a guide specifically for that on mobile, that's a good feedback and I'll make sure to add it as a task.

Now here is what you should do in order to achieve this:

For sorting, we recommend the following [guide](https://www.algolia.com/doc/guides/ranking/sorting/). Basically, the best way to deal with sorting is to create Algolia replicas indices that will have your data sorted in a particular way. In that way, you ensure that the performance of your query is lightning fast. 

On the iOS side, what you'll have to do is:
1- Make sure you're in MultiIndex mode by following [this guide](https://community.algolia.com/instantsearch-ios/getting-started-part2.html#display-data-from-multiple-hits). 
2- When the user switches the sort mode, you just target the new replica index by changing the value of the [index](https://github.com/algolia/instantsearch-ios/blob/9bea968c812042efb0906b25008f838a9edafa8d/Sources/Concrete/View/HitsTableWidget.swift#L21) property that is found in the HitsTableWidget.

If you're not using widgets specifically, and just using a `Searcher` or `Index`, then what you'll have to do is change the value of the `index` there to reflect the new targeted replica index. 

Best,
