### ISSUE TITLE
ResultingDelegate not working with custom widget when using multiple indices

### ISSUE THREAD

**Issue by aleincerto** [algolia/instantsearch-ios#43]
Hello,

I have MKMapView extending the ResultingDelegate and implementing the on(results: SearchResults?, error: Error?, userInfo: [String: Any]) method, very similar to https://github.com/algolia/instantsearch-ios-examples/blob/master/Icebnb/Icebnb/MapViewWidget.swift.

I had been using a single index and this seemed to work fine, the on() method would get called after each Algolia search. However, I recently started using multiple indices and now the on() method of my MKMapView is not being called anymore. Looking at the code in InstantSearch.swift it seems like when calling InstantSearch.shared.registerAllWidgets(in: self.view) my custom widget should get added to the ResultingDelegates and thus it should work. What am I missing?

As a workaround I did:
        InstantSearch.shared.getSearcher(named: Indeces.MAIN_INDEX)?.addResultHandler(mapView.on(results:error:userInfo:))
        InstantSearch.shared.getSearcher(named: Indeces.SORTED_BY_RATING)?.addResultHandler(mapView.on(results:error:userInfo:))

and that seemed to fix my issue. However, shouldn't this happen automatically when registering the widgets?

Thank you

**Comment by spinach** [comment]
Hey @aleincerto,

Thanks for contacting us. I investigated the above and this is definitely a valid point you're making. What you're trying to do is currently not documented, and we'll make sure to add this soon. 

So to answer your question:

The `addResultHandler` is one way to do it indeed.

In order to do make it work with custom widgets, you need your custom widget to implement the protocol `SearchableMultiIndexViewModel`, which basically requires you to add a property `searcherIds: [SearcherId]`. You need to fill this property with the indices that you want the widget to "tune into". When you do so, the `on()` method should be called for all the indices specified. Note that you'll also need to implement `func configure(withSearchers searchers: [Searcher])`, but you can leave it empty if you don't need to use the `searchers` associated to that widget.

Also note that as soon as you're using multi-indexing with InstantSearch, then your custom widget will have to implement `SearchableIndexViewModel` in case they're targeting **only 1 index** (what I explained right above is for multiple indices). Here you'll have to add the property `searcherId: SearcherId` and implement `func configure(with searcher: Searcher)`.

Thanks again for reporting this and let us know if you face any issue.

**Comment by aleincerto** [comment]
Thanks a lot for the help! I might come back to you with some other questions later on. This InstantSearch framework is really good, nice stuff that you have going on in here. Keep it up.

**Comment by spinach** [comment]
Thank you for the nice comment! Make sure to contact us if you face any other issues, we're always looking for feedback and ways to improve the library.
