### ISSUE TITLE
Overriding Widgets' protocols implementation

### ISSUE THREAD

**Issue by MohamedRed** [algolia/instantsearch-ios#52]
Hello,

I would like to call a function when I receive results after a search(). If I understand correctly the implementation of the protocol "ResultingDelegate" enables to act on the search results.
I wonder if there is a way to override the implementation of the protocols in the widgets like the search bar widget for instance. 
Or do we need to create a new widget ? It would not be very good because I don't want to miss all the functionalities of the Search Bar Widget.

Thanks in advance for your help.

**Comment by spinach** [comment]
Hello,

Thanks for contacting us! 

There are 3 ways you can "extend" the functionalities of a widget.

1- Custom widgets: [docs](https://community.algolia.com/instantsearch-ios/widgets.html#custom-widgets) -- [example widget in our example repo](https://github.com/algolia/instantsearch-ios-examples/blob/43b1811ee4727dcd347f830b69b62e2a0638c2dc/Icebnb/Icebnb/MapViewWidget.swift#L14)

2- ViewModels: they encapsulate the business logic of most of our widgets so that you can use them. [docs](https://community.algolia.com/instantsearch-ios/concepts.html#viewmodels).

3- InstantSearch Core: Offers the core functions for searching and filtering. Searcher is the main component, and you can access it by doing `InstantSearch.shared.getSearcher()`. [Docs](https://community.algolia.com/instantsearch-core-swift/guide/search.html). There is a search function there with a handler to listen to results.  

Let me know if you still need pointers!
