### ISSUE TITLE
Crash due to key value observer in iOS 9

### ISSUE THREAD

**Issue by arasu01** [algolia/instantsearch-ios#66]
**Describe the bug 🐛**

When run in the instant search in iOS 9 getting a below crash.

2019-01-11 12:37:53.071 YosiMD[5517:107780] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x7fb174947c00 of class InstantSearchCore.SearchParameters was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x7fb17494f120> (
<NSKeyValueObservance 0x7fb174948670: Observer: 0x7fb17494a6b0, Key path: query, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x7fb174947d10>
)'

**To Reproduce 🔍**
1. I have create an instance of viewcontroller.
2. Then added instant search instance to it.
3. Added it as child view controller to another view
4. It works fine. Then removed the view controller view.
5. Again add it the same view controller as subview.
6. It crashes with above code. 
7. This crash is happening only in iOS 9 and iOS 10.

**Expected behavior 💭**
it should crash, the same code works in iOS 11.

**Screenshots 🖥**

**Environment:**
 - OS: iOS
 - Version 9.3, 10.3 

**Additional context**
Please fix the issue as this was in the happening in the production build. Many users are affected due to it.

**Comment by spinach** [comment]
Hi @arasu01 - thanks for reporting this. After researching this, it seems related to an Apple bug ([SO thread that explains it](https://stackoverflow.com/a/50052623/905425)). My guess is that the crash is happening [here](https://github.com/algolia/instantsearch-ios/blob/84c08ab5290200d30bfddd768952bd62d80396b3/Sources/Concrete/ViewModel/SearchViewModel.swift#L49), and due to the bug, we need to deallocate the observation. Will let you know when this is fixed, I will submit a quick fix to avoid this bug

**Comment by arasu01** [comment]
@spinach : Thanks for the update. As a quick note we are using this objective-c project.

**Comment by spinach** [comment]
Hi @arasu01 - Try v 3.1.3 by doing `pod update` and see if that solves your issue! 

Cheers

**Comment by arasu01** [comment]
@spinach : It works now. Thanks
