### ISSUE TITLE
Deserializing hits blocks main thread

### ISSUE THREAD

**Issue by YANOUSHek** [algolia/instantsearch-ios#87]
**Describe the bug 🐛**
We ran into a performance issue when updating to the newest version of InstantSearch. While most of the migration from version 3.x went smooth we ran into multiple performance issues blocking main thread and the whole app UI when using search-as-you-type. It turned out that our search objects got bloated by a bug on our end but still this should not block the app UI just to do JSON deserialization on main thread.

**To Reproduce 🔍**
Use an index where search documents are large (ours were about 50kB per item).

**Expected behavior 💭**
The app should show search results with a bigger delay but should not block the user from typing.

**Environment:**
 - OS: iOS
 - Version 13.2

**Additional context**
It looks like the whole deserialization of the payload should be taken away from main thread to make sure we don't block UI with non-UI related tasks.

P.S. Why does `HitsInteractor` require the `Record` generic to implement `Codable` wouldn't `Decodable` be enough?

**Comment by spinach** [comment]
Hey @YANOUSHek ,

Thanks a lot for reporting this.

We are aware of this, and actually have a work in progress branch in order to solve this issue. In our `InstantSearchCore` library which is a dependency on `InstantSearch`, we have branch `feat/sync` that solves this issue. We're working on finishing this up this week and release a new version.

Concerning your P.S, it's a good point, we can make them `Decodable` if I am not mistaken, thanks for pointing this out! 

We'll let you know when we submit the fix. If time is of the essence for you, you can point `InstantSearchCore` to the `feat/sync` branch in your pod.

**Comment by spinach** [comment]
Fixed in 6.3.0 of InstantSearchCore. Run `pod update` to get the fix. Thank you for your patience!
